"""updated default value for is_active

Revision ID: 30598ecf0938
Revises: b41241d1fa3e
Create Date: 2024-05-07 18:50:06.880787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30598ecf0938'
down_revision = 'b41241d1fa3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
