"""removed slug from blog

Revision ID: 9a9c190ac958
Revises: ab768df5d025
Create Date: 2024-05-07 18:25:04.997159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9c190ac958'
down_revision = 'ab768df5d025'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
