"""updated blog view

Revision ID: b41241d1fa3e
Revises: 9a9c190ac958
Create Date: 2024-05-07 18:47:06.721157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41241d1fa3e'
down_revision = '9a9c190ac958'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
